### PR TITLE
Fail-safe connection to db

### LINKED ISSUE #104: fail-safe connection to db
App should not crash if db is not available, it should reconnect instead.

### PR DESCRIPTION
**Pull request by ITarako**
Closes #104

### CODE REVIEW

File: domain/src/mongo.js [hunk 1]
```diff
@@ -10,7 +10,14 @@ let db = undefined;
  * @returns {Promise.<Object, Error>} БД
  */
 async function connect(url) {
-    db = await mongo.connect(url);
+    do {
+        try {
+            db = await mongo.connect(url);
+        } catch (e) {
+            continue;
```
Comment (Eoksni) [inline domain/src/mongo.js]: use setTimeout or setInterval
your current solution is thread blocking and utilizes close to 100% cpu probably

**Review by Eoksni — CHANGES_REQUESTED** [review]

File: domain/src/mongo.js [hunk 2]
```diff
@@ -10,14 +10,18 @@ let db = undefined;
...
-        } catch (e) {
-            continue;
-        }
+    try {
+        db = await mongo.connect(url);
+    } catch (err) {
+        let intervalID = setInterval(async function () {
+            try {
+                db = await mongo.connect(url);
+                clearInterval(intervalID);
```
Comment (Eoksni) [inline domain/src/mongo.js]: what if an exception happens in the `clearInterval` call? it will be silently ignored by your code, not good
if you `await` the result of this top-level `connect` function, when will it be resolved if mongo connection fails for the first try?

**Review by Eoksni — CHANGES_REQUESTED** [review]

File: domain/src/mongo.js (hunk 2 above)
Comment (Eoksni) [reply domain/src/mongo.js]: let me know if you understand how to fix it, if not, I'll give more info

**Review by Eoksni — APPROVED** [review]
